spring:

  jpa:
    show-sql: true
    hibernate-ddl-auto: validate

  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${EVM_SERVER_URL:localhost:5432}/${DB_NAME:evm}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:evm}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:nulome}
