server:
  port: ${SERVER_PORT:8080}

spring:
  profiles.active: ${VALUE_PROFILE:dev}
  jpa:
    hibernate-ddl-auto: validate
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
  sql.init.mode: always

logging:
  level:
    httpclient:
      wire: DEBUG
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
          transaction: INFO
          transaction.interceptor: TRACE

ewm-server:
  url: ${EVM_SERVER_URL:http://localhost:8080}

