spring:

  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:wg
    username: sa
    password: ${MEM_H2_PASS:test}

  h2:
    console:
      enabled=: true
      path: /h2