version: '3.8'

services:
  stats-db:
    image: postgres:16.1
    container_name: stat-db
    ports:
      - "5669:5432"
    environment:
      - POSTGRES_DB=stat-service-db
      - POSTGRES_USER=statsUserDB
      - POSTGRES_PASSWORD=statsDB

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


  stats-server:
    build: stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - VALUE_PROFILE=dev
      - SERVER_PORT=9090
      - DB_NAME=stat-service-db
      - POSTGRES_USER=statsUserDB
      - POSTGRES_PASSWORD=statsDB
      - DB_HOST=stats-db
      - DB_PORT=5432
    #      - TZ=Europe/Samara
    #      - PGTZ=Europe/Samara


  ewm-service:
    build: main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db
    environment:
      - VALUE_PROFILE=dev
      - SERVER_PORT=8080
      - DB_NAME=main-ewm-db
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - STATS_SERVER_URL=http://stats-server:9090
      - POSTGRES_USER=mainUserDB
      - POSTGRES_PASSWORD=mainDB

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5670:5432"
    environment:
      - POSTGRES_DB=main-ewm-db
      - POSTGRES_USER=mainUserDB
      - POSTGRES_PASSWORD=mainDB

    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10